using SolarSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SolarSystem.Services
{
    public class MockLocalizationService : ILocalizationService
    {
        #region fields
        private List<StringResources> _stringResources;
        
        #endregion

        #region Constructor
        public MockLocalizationService()
        {
            StringResources = new List<StringResources> {
                new StringResources{LanguageId = 1, Name = "page.lang", Value = "en"},
                new StringResources{LanguageId = 2, Name = "page.lang", Value = "hu"},
                new StringResources{LanguageId = 3, Name = "page.lang", Value = "dk"},

                new StringResources{LanguageId = 1, Name = "index.sun", Value = "Sun"},
                new StringResources{LanguageId = 2, Name = "index.sun", Value = "Nap"},
                new StringResources{LanguageId = 3, Name = "index.sun", Value = "Solen"},

                new StringResources{LanguageId = 1, Name = "index.mercury", Value = "Mercury"},
                new StringResources{LanguageId = 2, Name = "index.mercury", Value = "Merkúr"},
                new StringResources{LanguageId = 3, Name = "index.mercury", Value = "Merkur"},

                new StringResources{LanguageId = 1, Name = "index.venus", Value = "Venus"},
                new StringResources{LanguageId = 2, Name = "index.venus", Value = "Vénusz"},
                new StringResources{LanguageId = 3, Name = "index.venus", Value = "Venus"},

                new StringResources{LanguageId = 1, Name = "index.earth", Value = "Earth"},
                new StringResources{LanguageId = 2, Name = "index.earth", Value = "Föld"},
                new StringResources{LanguageId = 3, Name = "index.earth", Value = "Jorden"},

                new StringResources{LanguageId = 1, Name = "index.moon", Value = "Moon"},
                new StringResources{LanguageId = 2, Name = "index.moon", Value = "Hold"},
                new StringResources{LanguageId = 3, Name = "index.moon", Value = "Månen"},

                new StringResources{LanguageId = 1, Name = "index.mars", Value = "Mars"},
                new StringResources{LanguageId = 2, Name = "index.mars", Value = "Mars"},
                new StringResources{LanguageId = 3, Name = "index.mars", Value = "Mars"},

                new StringResources{LanguageId = 1, Name = "index.jupiter", Value = "Jupiter"},
                new StringResources{LanguageId = 2, Name = "index.jupiter", Value = "Jupiter"},
                new StringResources{LanguageId = 3, Name = "index.jupiter", Value = "Jupiter"},

                new StringResources{LanguageId = 1, Name = "index.saturn", Value = "Saturn"},
                new StringResources{LanguageId = 2, Name = "index.saturn", Value = "Szaturnusz"},
                new StringResources{LanguageId = 3, Name = "index.saturn", Value = "Saturn"},

                new StringResources{LanguageId = 1, Name = "index.uranus", Value = "Uranus"},
                new StringResources{LanguageId = 2, Name = "index.uranus", Value = "Uránusz"},
                new StringResources{LanguageId = 3, Name = "index.uranus", Value = "Uranus"},

                new StringResources{LanguageId = 1, Name = "index.neptune", Value = "Neptune"},
                new StringResources{LanguageId = 2, Name = "index.neptune", Value = "Neptunusz"},
                new StringResources{LanguageId = 3, Name = "index.neptune", Value = "Neptun"},

                new StringResources{LanguageId = 1, Name = "index.pluto", Value = "Pluto"},
                new StringResources{LanguageId = 2, Name = "index.pluto", Value = "Pluto"},
                new StringResources{LanguageId = 3, Name = "index.pluto", Value = "Pluto"},

                new StringResources{LanguageId = 1, Name = "details.earth", Value = "Our home planet is the third planet from the Sun, and the only place we know of so far that’s inhabited by living things. While Earth is only the fifth largest planet in the solar system, it is the only world in our solar system with liquid water on the surface. Just slightly larger than nearby Venus, Earth is the biggest of the four planets closest to the Sun, all of which are made of rock and metal. The name Earth is at least 1,000 years old. All of the planets, except for Earth, were named after Greek and Roman gods and goddesses. However, the name Earth is a Germanic word, which simply means “the ground.”"},
                new StringResources{LanguageId = 2, Name = "details.earth", Value = "A mi bolygónk a harmadik bolygó a Naptól, és jelenlegi tudomásunk szeerint az egyetlen hely amit élőlények laknak. Míg a Föld csak az ötödik legnagyobb bolygó a naprendszerben, ez az egyetlen bolygó folyékony vízzel a felszínén. Csak némileg nagyobb a közeli Vénusznál, mégis a Föld a legnagyobb a négy napközeli bolygó közül, amely mind sziklás és fémes felépítésű. A Föld név legalább 1000 éves. A Földet leszámítva az összes bolygó görög és római istenek és istennők után lett elnevezve. Nevét egy germán eredetű szóról kapta, melynek jelentése föld."},
                new StringResources{LanguageId = 3, Name = "details.earth", Value = "Vores hjem planet er den tredje planet fra Solen, og det eneste sted vi kender til indtil nu, som er beboet af levende ting. Mens Jorden kun er den femte største planet i vores solsystem, er den den eneste planet i vores solsystem som har flydende vand på overfladen. Kun en smugle større end den tæt liggende Venus, er Jorden den største af de fire planeter tættest solen, af alle som er lavet af sten og metal. Navnet Jorden, er mindst 1.000 år gammelt. All planeterne, undtagen Jorden, er opkaldt efter græske og romerske guder, og gudinder. Dog er navnet \"Jorden\" et Germanisk ord, som simpelt oversat betyder \"Jorden\"."},

                new StringResources{LanguageId = 1, Name = "details.jupiter", Value = "Fifth in line from the Sun, Jupiter is, by far, the largest planet in the solar system, more than twice as massive as all the other planets combined. Jupiter’s familiar stripes and swirls are actually cold, windy clouds of ammonia and water, floating in an atmosphere of hydrogen and helium. Jupiter’s iconic Great Red Spot is a giant storm bigger than Earth that has raged for hundreds of years. Jupiter is surrounded by dozens of moons.Jupiter also has several rings, but unlike the famous rings of Saturn, Jupiter’s rings are very faint and made of dust, not ice. As a gas giant, Jupiter doesn’t have a true surface.The planet is mostly swirling gases and liquids."},
                new StringResources{LanguageId = 2, Name = "details.jupiter", Value = "A Jupiter az ötödik a naptól számítva, a naprendszer legnagyobb bolygója,több mint kétszer olyan nehéz mint az összes többi bolygó összeadva. Jellegzetes csdíkjai és örvényei hideg,szeles, ammóniából és vízből álló felhők, egy hidrogén és hélium alapú atmoszférában lebegve. A Jupiter ikonikus Nagy Vörös Pontja egy hatalmas vihar, ami nagyobb mint a Föld,és évszázadok óta tombol. Több tucat holddal van körülvéve, és több gyűrűje is van, viszont a Szaturnusz híres gyűrűivel ellentétben ezek halvány, porból állóak. Gázóriásként nincs tényleges felszíne, főképp örvénylő gázokból és folyadékokból áll."},
                new StringResources{LanguageId = 3, Name = "details.jupiter", Value = "Femte planet i lnje fra solen, er Jupiter. Uden tvivl den største planet i vores solsystem, mere end to gange så meget masse, som alle andre planeter sammenlagt. Jupiters genkendelige striper, og hvirvler er faktisk kolde, vindige skyer af Amoniak og vand, som svæver i en atmosfære af Hydrogen og helium. Jupiters ikoniske \"Great Red Spot\" er en gigantisk storm, større end selve jorden, og den har varet i flere hundrede år. Jupiter er omringet af dusinvis af måner. Jupiter har også flere ringe, men ulig den famøse ring af saturn, er Jupiters ringe meget svag, og lavet af støv og ikke is. Som en gas gigant, har Jupiter ikke en sand overflade. Planeten er primært bestående af hvirvlende gasser og væsker."},

                new StringResources{LanguageId = 1, Name = "details.mars", Value = "​Mars is the fourth planet from the Sun – a dusty, cold, desert world with a very thin atmosphere. Mars is also a dynamic planet with seasons, polar ice caps, canyons, extinct volcanoes,and evidence that it was even more active in the past. Mars is one of the most explored bodies in our solar system, and it’s the only planet where we’ve sent rovers to roam the alien landscape. NASA currently has two rovers (Curiosity and Perseverance), one lander (InSight), and one helicopter (Ingenuity) exploring the surface of Mars. Perseverance rover – the largest, most advanced rover NASA has sent to another world – touched down on Mars on Feb. 18, 2021, after a 203-day journey traversing 293 million miles (472 million kilometers). The Ingenuity helicopter rode to Mars attached to the belly of Perseverance. Perseverance is one of three spacecraft that arrived at Mars in 2021. The Hope orbiter from the United Arab Emirates arrived on Feb. 9, 2021. China’s Tianwen-1 mission arrived on Feb. 10, 2021, and includes an orbiter, a lander, and a rover. Europa and India also have spacecraft studying Mars from orbit. In May 2021, China became the second nation to ever land successfully on Mars when its Zhurong Mars rover touched down. An international fleet of eight orbiters is studying the Red Planet from above including three NASA orbiters: 2001 Mars Odyssey, Mars Reconnaissance Orbiter, and MAVEN. These robotic explorers have found lots of evidence that Mars was much wetter and warmer, with a thicker atmosphere, billions of years ago."},
                new StringResources{LanguageId = 2, Name = "details.mars", Value = "A Mars a negyedik bolygó a naptól, egy poros, hideg, sivatagos bolygó egy nagyon vékony atmoszférával. Dinamikus bolygó, évszakokkal,sarki jégsapkákkal,kanyonokkal, kihalt vulkánokkal és bizonyítékokkal hogy a múltban még aktívabb volt. A Mars az egyik legjobban kutatott égitest a naprendszerben, és az egyetlen amire robotokat küldtünk hogy felfedezzék a földönkívüli tájat. A Nasa-nak jelenleg két felderítő robotja(Curiosity és Perserverance), egy leszáló egység(InSight), és egy helikopter(Ingenuity)amelyek mind felfedezik a mars felszínét. A Perserverance a legnagyobb,legfejlettebb robot amit a NASA egy másik bolygóra küldött. 2021. február 18.-án landolt , egy 203 napos út során, 472 millió kilóméter utazás után. Az Ingenuity helikopter a Perserverance aljáhot rögzítve utazott. Perserverance egy a három közül ami 2021-ben érkezett a marsra. A Hope műhold az Egyesült Arab Emírségekből érkezett 2021 február 9.-én. A kínai Tiawen-1 küldetés február 10.-én érkezett, és egy műhold,egy leszálló és egy felderítő. Európának és Indiának is van műholdja ami a Marsot tanulmányozza. 2021 májusában Kína lett a második nemzet ami sikeresen landolt, a Zhurong nevű marsjárójával. Nyolc nemzetközi műhold tanulmányozza a vörös bolygót,közöttük három NASA műhold: 2001 Mars Odyssey, Mars Reconnaisance műhold, és a MAVEN. Ezek a robotikus felfedezők rengeteg bizonyítékot találtak, hogy a mars évmilliárdokkal ezelőtt sokkal vizesebb és melegebb volt, vastagabb atmoszférával."},
                new StringResources{LanguageId = 3, Name = "details.mars", Value = "Mars er den fjerde planet fra solen - en støvet, kold, ørken verden, med en meget tynd atmosfære. Mars er også en dynamisk planet, med årstider, polar ice, kløfter, uddøde vulkaner, og beviser for at den var mere aktiv før hen. Mars er en af de mest udforskede planeter i vores solsystem, og det er den eneste planet hvor vi har sendt \"Rovers\" for at køre på det fremmede landskabet. NASA har i øjeblikket to \"rovers\"(Curiosity og Perseverance), en lander(InSigth), og en helikopter(Ingenuinity) som udforsker overfladen af Mars. Perseverance roveren - den største, mest avancerede rover NASA har sendt til andre verdener - landede på Mars den 18.februar, 2021, efter en 203 dages lang rejse, over 293 millioner mil(472 millioner kilometer). \"Ingenuity\" helikopteren fløj sammen med Perseverance op til Mars. Perseverance er en af de tre rumfartøjer som ankom til mars i 2021. \"The hope orbiter\" fra de forenede emirater, ankom den 9.februar, 2021.Kinas \"Tianwen-1\" mission ankom den 10.februar 2021 og inkludered en orbiter, en lander og en rover. I may 2021, blev Kinda den anden nation til nogensinde at successfuldt lande på Mars, da dens \"Zhurong Mars Rover\" landede. En international flåde af otte orbiters  som studere den røde planet ovenfra, inklusiv tre NASA orbiters: 2001 Mars Odyssey, Mars Reconnaissance Orbiter, og MAVEN. Disse robotiske udforskere har fundet mange beviers på at Mars var meget vådere og farmere, med en tyk atmosfære for billioner af år siden."},

                new StringResources{LanguageId = 1, Name = "details.mercury", Value = "​Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun’s planets. Mercury rotates in a way that is unique in the Solar System. Mercury’s axis has the smallest tilt of any of the Solar System’s planets. Mercury’s surface appears heavily cratered and is similar in appearance to the Moons, indicating that it has been geologically inactive for billions of years. Having almost no atmosphere to retain heat, it has surface temperatures that vary diurnally more than on any other planet in the Solar System, ranging from −173°C at night to 427°C during the day across the equatorial regions. Mercury is one of four terrestrial planets in the Solar System, and is a rocky body like Earth. It is the smallest planet in the Solar System."},
                new StringResources{LanguageId = 2, Name = "details.mercury", Value = "A Mercury a naprendszer legkisebb bolygója, és a legközelebbi a naphoz. Napkörüli pályája 87.97 földi napot vesz igénybe, a legkevesebbet a naprendszerben. Forgása a naprendszerben egyedi,tengelye a legkisebb dőlésszögű. Felszíne erősen kráteres és nagyon hasonló a Holdhoz,többmilliárd éves geológiai inaktivitást jelezve. Szinte semmi atmoszférája sincs hogy megtartsa a hőt, ezért a felszíni hőmérséklete naponta többet változik mint bármely másik bolygón,az éjjeli -173°C-tól egészen a nappali 427°C-ig,az egyenlítői területeken. A Mercury egy a naprendszer négy föld típusú,kőzet alapú bolygójából."},
                new StringResources{LanguageId = 3, Name = "details.mercury", Value = "Merkur er den mindste planet i vores solsystem og den planet som er tættest på solen. En omkreds om solen tager 87.97 jord dage, hvilket er det korteste af alle solens planeter. Merkur rotere på en måde som er unik i dette solsystem. Merkurs akse har det mindste tilt af alle planeter i vores solsystem. Merkurs overflade fremstår tunkt dækket af kratere, og minder meget om månens, hvilket indikere at den har været geologisk inaktiv i billioner af år. Næsten uden atmosfære til at holde på varmen, har Merkur den mest svingende overflade temperatur af alle planeterne i vores solsystem, med temperature svingende fra −173°C om natten til 427°C hen over dagen i nogle regioner. Merkur er en af de fire jordiske planeter i solsystemet, og har en stenet struktur ligesom Jorden. Det er den mindste planet i vores solsystem."},
                
                new StringResources{LanguageId = 1, Name = "details.moon", Value = "​The Moon is Earth’s only natural satellite. At about one-quarter the diameter of Earth (comparable to the width of Australia), it is the largest natural satellite in the Solar System relative to the size of a major planet. The fifth largest satellite in the Solar System overall, and larger than any known dwarf planet. It lacks any significant atmosphere, hydrosphere, or magnetic field. Its surface gravity is about one-sixth of Earth’s (0.1654 g); Jupiter’s moon Io is the only satellite in the Solar System known to have a higher surface gravity and density. The most widely accepted origin explanation posits that the Moon formed about 4.51 billion years ago, not long after Earth, out of the debris from a giant impact between the planet and a hypothesized Mars-sized body called Theia. It then receded to a wider orbit because of tidal interaction with the Earth. The near side of the Moon is marked by dark volcanic maria(\"seas\"), which fill the spaces between bright ancient crustal highlands and prominent impact craters."},
                new StringResources{LanguageId = 2, Name = "details.moon", Value = "A Hold a Földnek az egyetlen természetes műholdja. Körülbelül egy negyede az átmérője a Fölhöz viszonyítva (szélessége Ausztráliával) ez a legnagyobb természetes műhold a Naprendszerben a főbolygókhoz viszonyítva. Az ötödik legnagyobb hold a Naprendszerben és nagyobb mint az eddig ismert törpebolygók. Nincs jelentős atmoszférája, hidroszférája vagy mágneses mezője.A felszíni gravitációja körülbelül egy hatoda a Földének (0.1654 g); a Jupiter holdja az Io az egyetlen hold a Naprendszerben amiről tudjuk, hogy nagyobb felszíni gravitációval és sűrűséggel rendelkezik. A legszélesebb körben elfogadott eredet történet alapján a Hold kialakulása körülbelül 4.51 milliárd évvel ezelőtt történt, nem sokkal a Föld után, a Föld és a feltételezett Mars - méretű Theia bolygó ütközésének törmelékéből. Ezután szélesebb pályára vonult vissza a Földdel való árapály - kölcsönhatás miatt. A Hold Föld felőli oldalán látható holdmáriák nagy, sötét, bazaltos síkságok, amelyet ősi aszteroida becsapódások alkottak.Máriának, latinul „tengereknek” nevezték el őket a korai csillagászok, akik összetévesztették őket a valódi tengerekkel."},
                new StringResources{LanguageId = 3, Name = "details.moon", Value = "Månen er jordens eneste naturlige satelit. Med omkring en kvartende del af jordens diameter (Svare til bredden af Australien), er det den største naturlige satelit i vores solsystem, relativt til størrelsen af en større planet. Den femte største satelit i vores solsystem generelt, og større end nogle af de andre kendte dværg planeter. Den mangler dog en vigtig atmosfære, hydrosfære og magnetisk felt. Dens overflade tyngdekraft er omkring en sjettedel af jordes. Jupiters måne \"Io\" er den eneste saltelit i vores solsystem kendt for at have en højere overflade tyngdekraft og densitet. Den mest acceptered oprindelses forklaring mener at månen formede omkring 4.51 billioner år siden, ikke længe efter Jorden, ud af fragmenter af et kæmpe nedsplag mellem planeten og en hypotetisk mars - størrelse komet kalled Theia. Den træk sig ud i et bredere kredsløb på grund af tidevands interaction med Jorden. Den nære side af Månen er markede af en mørke vulkaniske søer, som fylder mellemrumet mellem de klare deformerede højlande samt tydelige nedslags kratere."},
                
                new StringResources{LanguageId = 1, Name = "details.neptune", Value = "Dark, cold, and whipped by supersonic winds, the ice giant Neptune is the eighth and most distant planet in our solar system. More than 30 times as far from the Sun as Earth, Neptune is the only planet in our solar system not visible to the naked eye, and the first predicted by mathematics before its discovery. In 2011 Neptune completed its first 165-year orbit since its discovery in 1846. NASA’s Voyager 2 is the only spacecraft to have visited Neptune up close. It flew past in 1989 on its way out of the solar system."},
                new StringResources{LanguageId = 2, Name = "details.neptune", Value = "Sötét, hideg és  szuperszonikus szelekkel felkorbácsolt, a jégóriás Neptunusz a nyolcadik, és legtávolabbi bolygó a naprendszerünkben. Több mint harmincsszor távolabb van a naptól mint a föld, az egyetlen bolygó amit nem láthatunk szabad szemmel, és az első bolygó ami matemaitka átlal meg volt jósolva a felfedezése előtt. 2011-ben befejezte első napkörüli pályáját az 1846-os felfedezése óta. A NASA Voyager 2 műholdja az egyetlen ami közelről meglátogatta. 1989-ben repült el mellette, a naprendszerből való távozása előtt."},
                new StringResources{LanguageId = 3, Name = "details.neptune", Value = "'Mørk, kold, og pisked af supersoniske vinde, er is giganten Neptun den ottende mest fjerne planet i vores solsystem. Mere end 30 gange så fjern fra solen som Jorden, er neptun den eneste planet som vi ikke kan se med det blotte øje, og bløv først forudsagt af matematikere før dens opdagelse. I 2011 færdiggjorde Neptun sit første 165 års kredsløb siden dens opdagelse i 1846. NASA’s Voyager 2, er det eneste rumfartøj som har besøg Neptun, tæt på. Det fløj forbi i 1989 på vej ud af solsystemet."},

                new StringResources{LanguageId = 1, Name = "details.pluto", Value = "Pluto is a dwarf planet in the Kuiper Belt, a donut-shaped region of icy bodies beyond the orbit of Neptune. There may be millions of these icy objects, collectively referred to as Kuiper Belt objects (KBOs) or trans-Neptunian objects (TNOs), in this distant region of our solar system. Pluto – which is smaller than Earth’s Moon – has a heart-shaped glacier that’s the size of Texas and Oklahoma. This fascinating world has blue skies, spinning moons, mountains as high as the Rockies, and it snows – but the snow is red. On July 14, 2015, NASA’s New Horizons spacecraft made its historic flight through the Pluto system – providing the first close-up images of Pluto and its moons and collecting other data that has transformed our understanding of these mysterious worlds on the solar system’s outer frontier. In the years since that groundbreaking flyby, nearly every conjecture about Pluto possibly being an inert ball of ice has been thrown out the window or flipped on its head. “It’s clear to me that the solar system saved the best for last!” said Alan Stern, New Horizons principal investigator from the Southwest Research Institute, Boulder, Colorado. “We could not have explored a more fascinating or scientifically important planet at the edge of our solar system. The New Horizons team worked for 15 years to plan and execute this flyby and Pluto paid us back in spades!”"},
                new StringResources{LanguageId = 2, Name = "details.pluto", Value = "A Pluto egy törpebolygó a Kuiper övben, ami egy fánk alakú régió jeges égitestekkel a Neptunusz pályáján túl.Ezekből az égitestekből több millió van, az együttesüket KBO-nak (Kuiper Belt objects) vagy TNO-nak(Trans-Neptunian Objects) nevezzük. A Plutonak -ami kisebb a Föld holdjánál- van egy szív alakú gleccsere ami akkora mint Texas és Oklahoma. Ennek az elbűvölő világnak kék egei, forgó holdjai, és a Sziklás Hegységhez hasonlóan magas hegyei vannak.szinte folyamatosan havazik, ami piros színű. 2015 Július 14.-én a NASA New Horizons műholdja keresztül repült a Pluto rendszeren, az első közeli képeket szolgáltatva a Pluto-ról és holdjairól,és adatokat gyűjtött ami megváltoztatta tudásunkat ezekről a titokzatos világokról naprendszerünk külső határán. Az ezt követő évek során az összes sejtés,hogy a pluto egy élettelen jéggömb, ki lett dobva vagy fejére fordítva. \"Nekem egyértelmű hogy a naprendszerünk a legjobbat hagyta uloljára.\" mondta Alan Stern, a New Horizons fő kutatója a Délnyugati Kutatóintézetben, Coloradoban. \"Nem is tudtunk volna felfedezni ennél elbűvölőbb és tudományosan fontosabb bolygót a naprendszerunk határán.\" A New Horizons csapat 15 évig dolgozott hogy megtervezze és végrehajtsa ezt a felfedezést."},
                new StringResources{LanguageId = 3, Name = "details.pluto", Value = "Pluto er en dværgplanet i Kuiper bæltet, en donut-formet region af isede kometer ude af kredsløbet af Neptun. Der er måske millioner af disse isede kometer. Samlet refereret til som \"Kuiper Belt Objects (KBO’s)\" eller \"Trans-neptunian objects (TNO’s), i en fjern region af vores solsystem. Pluto - some r mindre end Jordens måne - har en stor hjerte-formet glecier, som er på størelse med Texas og Oklahoma. Denne fascinered verden har blå skyer, roterende måner, bjerge så høje som \"The Rockies\", og det sner - men sneen er rød. Den 14 Juli, 2015, fuldføre NASA’s \"New Horizons spacecraft\" sin historiske flyvning igennem Pluto’s system - hvilket gav os det første nærbillede af Pluto, og dens måner, samt andre data som transformerede vores forståelse af disse mystiske verdener, i yderkanten af vores solsystem. I årende efter den banebrydende gennemflyvning, er næsten alle teorier om at Pluto bare er en klump af is, enten blever kaseret, eller vendt på hovedet. \"Det er klart for mig at solsystemet gemte det bedste til sidst!\" sagde Alan Stern, \"New Horizons rektor efterforsker\" fra Southwest Research Institute, Boulder, Colorado. \"Vi kunne ikke have opdaget en mere fascinerende eller forsknings vigtigt planet, på kanten af vores solsystem. New Horizons holdet arbejdede i 15 år for at planlægge og eksevere denne forbiflyvning, og pluto betalte os tilbage i spandevis!\""},

                new StringResources{LanguageId = 1, Name = "details.saturn", Value = "Saturn is the sixth planet from the Sun and the second-largest planet in our solar system. Adorned with thousands of beautiful ringlets, Saturn is unique among the planets. It is not the only planet to have rings – made of chunks of ice and rock – but none are as spectacular or as complicated as Saturn’s. Like fellow gas giant Jupiter, Saturn is a massive ball made mostly of hydrogen and helium."},
                new StringResources{LanguageId = 2, Name = "details.saturn", Value = "A Szaturnusz a hatodik a naptól , és a második legnagyobb bolygó a naprendszerünkben. Gyűrűk ezreivel díszítve a Szaturnusz egyedi a bolygók között. Nem az egyetlen bolygó jégből és sziklákból álló gyűrűkkel, de egyik sem olyan lenyűgöző mint a Szaturnuszé. Mint a gázóriás társa,a Jupiter, A Szaturnusz is többségben hidrogénből és héliumból áll."},
                new StringResources{LanguageId = 3, Name = "details.saturn", Value = "Saturn er den sjette planet fra Solen, og er den anden-største planet i vores solsystem. Prydet (beklædt) med tusindvis af smukke ringe, er Saturn unik blandt planeterne. Det er ikke den eneste planet som har ringe - lavet af klumper af is og sten - dog er ingen andre så spektakulære eller kompliceret som Saturn’s. Ligesom den fælles gasgigant Jupiter, er saturn en massiv bold bestående mest af Hydrogen og Helium."},

                new StringResources{LanguageId = 1, Name = "details.sun", Value = "Our Sun is a 4.5 billion-year-old star – a hot glowing ball of hydrogen and helium at the center of our solar system. The Sun is about 150 million kilometers from Earth, and without its energy, life as we know it could not exist here on our home planet. The Sun is the largest object in our solar system. The Sun’s volume would need 1.3 million Earths to fill it. Its gravity holds the solar system together, keeping everything from the biggest planets to the smallest bits of debris in orbit around it. The hottest part of the Sun is its core, where temperatures top 15 million degrees Celsius. The Sun’s activity, from its powerful eruptions to the steady stream of charged particles it sends out, influences the nature of space throughout the solar system. NASA and other international space agencies monitor the Sun 24/7 with a fleet of spacecraft, studying everything from its atmosphere to its surface, and even peering inside the Sun using special instruments. Sun - exploring spacecraft include Parker Solar Probe, Solar Orbiter, SOHO, ACE, IRIS, WIND, Hinode, Solar Dynamics Observatory, and STEREO."},
                new StringResources{LanguageId = 2, Name = "details.sun", Value = "A Napunk egy 4.5 milliárd éves csillag, egy forró ragyogó gömb hidrogénből és héliumból, a naprendszerünk közepén. Nagyjából 150 millió kilóméterre van a Földtől, és az energiája nélkül a földi élet nem létezhetne. A Nap a legnagyobb égitest a naprendszerünkben, térfogata 1.3 milliószorosa a földnek. A gravitációja tartja egyben a naprendszert, a legkisebb törmeléktől a legnagyobb bolygókig mindent a pályáján tartva. A legforróbb pontja a mag, ahol több mint 15 millió °C van. A nap tevékenysége, a napkitörésektől a folyamatosan áramló töltött részecskékig, befolyásolja az űr természetét az egész naprendszeren belül. A NASA és más nemzetközi űr-ügynökségek a nap 24 órájában figyelik a napot,műholdak flottájával, tanulmányozva az atmoszférától a felszínig mindent. A nap felderítő műholdak:Parker Solar Probe, Solar Orbiter, SOHO, ACE, IRIS, WIND, Hinode, Solar Dynamics Observatory, és a  STEREO."},
                new StringResources{LanguageId = 3, Name = "details.sun", Value = "Vores Sol er en 4.5 billioner år gammel stjener - en varm glødende kugle af hydrogen og helium, som center for vores solsystem. Solen er omkring 150 millioner kilometer fra Jorden, og uden dens energy, ville livet som vi kender det ikke eksistere her på vordes planet. Solen er det største objekt i vores solsystem. Solen skulle have 1.3 millioner af jorden i sig for at blive fyldt. Dens tyngdekraft holder solsystemet sammen, holder alting fra den største planet, til den mindste smugle affald, eller meteoer i kredsløb omkring sig. Den varmeste del af solen er dens kerne, hvor temperaturen toppes med 15 millioner grader Celcius. Solens aktivitet, fra dens kraftfulde udbrud, til dens linde strøm af opladte partkiler den sender ud, påvirker den natur og rummet gennem solsystemet. NASA og andre internationale rum agenture måler solen 24 timer i døgnet 7 dage om ugen med en flåde af rumfartøjer, hvor de studere alt fra dens atmosføre, til dens overflade, selv kigge ind i solen ved brug af special udstyr. Sol - udforsknings fartøjer inkludere \"Parker Solar Probe\", \"Solar Orbiter\", \"SOHO\", \"ACE\", \"IRIS\", \"WIND\", \"Hinode\", \"Solar Dynamics Observatory\" og \"STEREO\"."},
                
                new StringResources{LanguageId = 1, Name = "details.uranus", Value = "Uranus is the seventh planet from the Sun, and has the third-largest diameter in our solar system. It was the first planet found with the aid of a telescope, Uranus was discovered in 1781 by astronomer William Herschel, although he originally thought it was either a comet or a star. Uranus is very cold and windy. The ice giant is surrounded by 13 faint rings and 27 small moons as it rotates at a nearly 90-degree angle from the plane of its orbit. This unique tilt makes Uranus appear to spin on its side, orbiting the Sun like a rolling ball."},
                new StringResources{LanguageId = 2, Name = "details.uranus", Value = "Az Uránusz a hetedik bolygó a naptól,és a harmadik legnagyobb átmérőjű a naprendszerben. Az első bolygó amit teleszkóp segítségével találtunk meg, 1781-ben egy William Herschel nevű csillagász által, bár először üstökösnek vagy csillagnak hitte. Az Uránisz nagyon hideg és szeles. A jégóriás 13 halvány gyűrűvel és 27 kis holddal van körülvéve, és közel 90°-os szögben kering a pályája síkjától. Ez az egyedi dőlésszög miatt az oldalán forog,úgy kering a nap körül mint egy guruló labda."},
                new StringResources{LanguageId = 3, Name = "details.uranus", Value = "Uranus er den syvende planet fra Solen, og har den tredje største diameter i vores solsystem. Den var den første planet som blev fundet ved hjælp af et telescope, Uranus blev opdaget i 1781 af astronom William Herschel, selvom han originalt troede det var en komet eller en stjerne. Uranus er en meget cold og vindig planet. Is giganten er omringet af 13 svage ringe, og 27 små måner, som den rotere med en næsten 90-graders vinkel. Denne unikke tiltning får Uranus til at se ud som om den rotere på sin side, og rotere rundt om solen som en rullende bold."},

                new StringResources{LanguageId = 1, Name = "details.venus", Value = "Venus is the second planet from the Sun and is Earth’s closest planetary neighbor. It’s one of the four inner, terrestrial planets, and it’s often called Earth’s twin because it’s similar in size and density. Venus has a thick, toxic atmosphere filled with carbon dioxide and it’s perpetually shrouded in thick, yellowish clouds of sulfuric acid that trap heat. It’s the hottest planet in our solar system, even though Mercury is closer to the Sun. Surface temperatures on Venus are about 475°C Venus has crushing air pressure at its surface – more than 90 times that of Earth – similar to the pressure you’d encounter a mile below the ocean on Earth. Another big difference from Earth – Venus rotates on its axis backward, compared to most of the other planets in the solar system. Venus was the first planet to be explored by a spacecraft."},
                new StringResources{LanguageId = 2, Name = "details.venus", Value = "A Vénusz a második bolygó a namtól,és a Föld legközelebbi szomszédja. Egy a négy belső, föld típusó bolygóknak, és gyakran hívják a föld ikrének mert hasonló méretű és sűrűségű. Vastag, mérgező atmoszférája van, szén-dioxiddal töltve, és örökké burkolt vastag, sárgás kénsav felhőkkel amik megtartják a hőt. A naprendszer legforróbb bolygója, annak ellenére hogy a Mercury közelebb van a naphoz. A felszíni hőmérséklet nagyjából 475°C. Hatalmas légnyomás van a felszínen -a földi nyomás 90-szerese- hasonló mint 2 kilóméterrel az óceán felszíne alatt. Egy másik nagy különbség, a Vénusz visszafele forog a tengelyén a naprendszer legtöbb bolygójához képest. A Vénusz volt az első bolygó amit műholddal fedeztek fel."},
                new StringResources{LanguageId = 3, Name = "details.venus", Value = "Venus er den anden planet fra Solen, og er jordens nærmeste plentære nabo. Den er en af de fire indre planetære planeter, og er often kaldet \"Jordens tvilling\", da de minder om hinanden i både størrelse og densitet. Venus har en tyk, giftig atmosfære, fyldt med carbon dioxid, og er dækket i tykke, gullige skyer af svolvsyre som fanger varme. Det er den varmeste planet i vores solsystem, selvom Merkur er tættere på solen. Overflade temperaturen på Venus er omkring 475°C. Venus har et knusende lufttryk på dens overflade - mere end 90 gange jordens lufttryk - svarende til hvad du ville føle 1,6 kilometer under havet på jorden. Endnu en stor forskel fra Jorden - Venus roteres baglæns på dens akse, sammenlignet med de fleste andre planeter i vores solsystem. Venus var den første planet som blev udforsket af et rumskib."}

            };
        }
        #endregion

        #region Methods
        public StringResources GetStringResources(string resourceKey, int languageId)
        {
            return StringResources.FirstOrDefault(sr => 
                sr.Name.Trim().ToLower() == resourceKey.Trim().ToLower()
                && sr.LanguageId == languageId);
        }
        #endregion

        #region Properties
        public List<StringResources> StringResources
        {
            get { return _stringResources; }
            set { _stringResources = value; }
        }
        #endregion
    }
}
